/*
 * config.h
 *
 *  Created on: Apr 14, 2017
 *      Author: paco
 */

#ifndef SRC_CONFIG_H_
#define SRC_CONFIG_H_

#define USE_OFX 1

#define GROUP_DETECTION_DISTANCE_THRESHOLD 1.5
#define INTERACTION_POTENTIAL_THRESHOLD 0.6
#define GAUSSIAN_SPACE_INFLUENCE_TRESHOLD 0.1

#define INTERACTION_MAX_TIME 5
#define SEEK_INTERACTION_MIN_TIME 15
#define ROBOT_MAX_ROT_DELTA_BEFORE_MOVE 0.2

#define UDP_SERVER_PORT 8888
#define IP_UDP_CLIENT "192.168.40.21"
#define ENABLE_CLIENT2 1
#define IP_UDP_CLIENT2 "192.168.40.19"

#endif /* SRC_CONFIG_H_ */
